version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.0
  snyk: snyk/snyk@0.1.0
  node: circleci/node@4.5.1
  docker: circleci/docker@1.6.0

jobs:
  snyk_dependency_check:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            npm install
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app'
          severity-threshold: high
          token-variable: SNYK_TOKEN
          target-file: package.json

  build_image:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          image: $DOCKERID/${CIRCLECI_PROJECT_REPONAME}:${CIRCLE_SHA1}
  scan_and_push_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - snyk/scan:
          docker-image-name: '$DOCKER_USERNAME/${CIRCLECI_PROJECT_REPONAME}:${CIRCLE_SHA1}'
          fail-on-issues: false
          monitor-on-build: true
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-container'
          severity-threshold: critical
          target-file: Dockerfile
          token-variable: SNYK_TOKEN
      - docker/check
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKERID/${CIRCLECI_PROJECT_REPONAME}:${CIRCLE_SHA1}
workflows:
  build_and_push:
    jobs:
      - snyk_dependency_check
      - build_image:
          requires:
            - snyk_dependency_check
      - scan_and_push_image:
          requires:
            - build_image

